// <auto-generated />
using Buddy.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Buddy.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Buddy.Models.Models.Category", b =>
                {
                    b.Property<int>("category_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("category_Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("category_Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            category_Id = 1,
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            category_Id = 2,
                            DisplayOrder = 2,
                            Name = "Sci-fi"
                        },
                        new
                        {
                            category_Id = 3,
                            DisplayOrder = 3,
                            Name = "History"
                        },
                        new
                        {
                            category_Id = 4,
                            DisplayOrder = 4,
                            Name = "Rom-Com"
                        });
                });

            modelBuilder.Entity("Buddy.Models.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imageurl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<double>("price100")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Robert T.",
                            CategoryId = 1,
                            Description = "Rich Dad Poor Dad is mainly about achieving financial literacy and independence by making money work for you, not the other way around. ",
                            ISBN = "3838971919",
                            Imageurl = "",
                            ListPrice = 10.0,
                            Name = "Rich Dad poor Dad",
                            Price = 500.0,
                            Price50 = 400.0,
                            price100 = 200.0
                        },
                        new
                        {
                            Id = 2,
                            Author = "Chethan Bhagath",
                            CategoryId = 2,
                            Description = "Half Girlfriend is a 2014 novel by Chetan Bhagat about a Bihari boy named Madhav who falls in love with a wealthy Delhi girl, Riya. ",
                            ISBN = "3832151919",
                            Imageurl = "",
                            ListPrice = 12.0,
                            Name = "Half Girlfriend",
                            Price = 600.0,
                            Price50 = 500.0,
                            price100 = 300.0
                        },
                        new
                        {
                            Id = 3,
                            Author = "S.S. Rajamouli",
                            CategoryId = 3,
                            Description = "Baahubali is a  Indian epic action series about a legendary warrior who rises from humble beginnings to reclaim his rightful throne in the kingdom of Mahishmati. ",
                            ISBN = "3838999919",
                            Imageurl = "",
                            ListPrice = 5.0,
                            Name = "Baahubali The Legend",
                            Price = 400.0,
                            Price50 = 200.0,
                            price100 = 100.0
                        });
                });

            modelBuilder.Entity("Buddy.Models.Models.Product", b =>
                {
                    b.HasOne("Buddy.Models.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
